#### HOTELS
GET http://localhost:9090/hotels

### CUARTOS POR HOTEL
GET http://localhost:9090/hotels/rooms/1

#### RESERVACIONES POR HOTEL
GET http://localhost:9090/hotels/reservations/2



#### obtener valores de properties
GET http://localhost:9090/hotels/read/properties



#### RESERVATIONS
GET http://localhost:9092/reservations

#### RESERVATIONS by room
GET http://localhost:9092/reservations/byroom/1



#### ROOMS
GET http://localhost:9091/rooms

#### ROOMS FILTRADO
GET http://localhost:9091/rooms/byHotel/1

#### ROOMS RESERVATIONS
GET http://localhost:9091/rooms/reservations/1




##### insertar nuevo produco
POST http://localhost:9091/rooms
Content-Type: application/json

{
     "descripcion":"xxssx",
     "precio":10.50
}



##### actualizar produco
PUT http://localhost:8080/api/producto/1
Content-Type: application/json

{
     "descripcion":"Agua",
     "precio":10.50
}




##### actualizar produco
DELETE  http://localhost:8080/api/producto/1
Content-Type: application/json

